version: 2.1
orbs:
  docker: circleci/docker@2.1.2

on:
  push:
    branches:
      - devops

jobs:
  build-and-test:
    description: Setup laravel application and run tests
    docker:
      # Specify the version you desire here
      - image: cimg/php:8.2-browsers

    steps:
      - checkout

      - run:
          name: "Prepare environment"
          command: |
            sudo apt update
      # Download and cache dependencies
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: "Install dependencies"
          command: composer install --prefer-dist --no-interaction

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor

      - run:
          name: "Create .env file and generate app key"
          command: |
            cp .env.example .env
            php artisan key:generate

  build-docker-image:
    executor:
      name: docker/docker
      tag: "3.6"
    steps:
      - checkout
      # Use the docker-compose orb for Docker-related steps
      - docker-compose/build
      - docker-compose/configure:
          image-name: prjg5noecontainer.azurecr.io/prjg5neo:latest
      - docker-compose/push:
          requires:
            - docker-compose/configure

workflows:
  test-and-deploy:
    jobs:
      - build-and-test
      - build-docker-image:
          requires:
            - build-and-test
