version: 2.1
orbs:
  docker: circleci/docker@2.1.2

on:
  push:
    branches:
      - devops

jobs:
  build-docker-image:
    executor:
      name: docker/docker
      tag: "3.6"
    steps:
      - checkout
      - docker/install-docker-tools
      - setup_remote_docker:
          version: 20.10.24
          docker_layer_caching: true
      - run:
          name: "Build and Push Docker image"
          command: |
            docker build . -t prjg5noecontainer.azurecr.io/prjg5neo:latest
            echo "$DOCKER_PASS" | docker login --username prjg5noecontainer --password-stdin prjg5noecontainer.azurecr.io
            docker push prjg5noecontainer.azurecr.io/prjg5neo:latest

workflows:
  test-and-deploy:
    jobs:
      - build-docker-image
