# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - prjg5noe

on:
  push:
    branches:
      - devops
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://prjg5noecontainer.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_4832ebed0a6d4a68a7bebc025d749e86 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_8690aa73fc22486ca4a7280d91185420 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: prjg5noecontainer.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_4832ebed0a6d4a68a7bebc025d749e86 }}/prjg5image:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'prjg5noe'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_0992ceac8f5f4ee9a974ac7a1fc42bc2 }}
        images: 'prjg5noecontainer.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_4832ebed0a6d4a68a7bebc025d749e86 }}/prjg5image:${{ github.sha }}'